/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TranslateRouteImport } from './routes/translate'
import { Route as TransitRouteImport } from './routes/transit'
import { Route as FoodRouteImport } from './routes/food'
import { Route as FactCheckRouteImport } from './routes/fact-check'
import { Route as CulturalRouteImport } from './routes/cultural'
import { Route as IndexRouteImport } from './routes/index'

const TranslateRoute = TranslateRouteImport.update({
  id: '/translate',
  path: '/translate',
  getParentRoute: () => rootRouteImport,
} as any)
const TransitRoute = TransitRouteImport.update({
  id: '/transit',
  path: '/transit',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodRoute = FoodRouteImport.update({
  id: '/food',
  path: '/food',
  getParentRoute: () => rootRouteImport,
} as any)
const FactCheckRoute = FactCheckRouteImport.update({
  id: '/fact-check',
  path: '/fact-check',
  getParentRoute: () => rootRouteImport,
} as any)
const CulturalRoute = CulturalRouteImport.update({
  id: '/cultural',
  path: '/cultural',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cultural': typeof CulturalRoute
  '/fact-check': typeof FactCheckRoute
  '/food': typeof FoodRoute
  '/transit': typeof TransitRoute
  '/translate': typeof TranslateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cultural': typeof CulturalRoute
  '/fact-check': typeof FactCheckRoute
  '/food': typeof FoodRoute
  '/transit': typeof TransitRoute
  '/translate': typeof TranslateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cultural': typeof CulturalRoute
  '/fact-check': typeof FactCheckRoute
  '/food': typeof FoodRoute
  '/transit': typeof TransitRoute
  '/translate': typeof TranslateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cultural'
    | '/fact-check'
    | '/food'
    | '/transit'
    | '/translate'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cultural' | '/fact-check' | '/food' | '/transit' | '/translate'
  id:
    | '__root__'
    | '/'
    | '/cultural'
    | '/fact-check'
    | '/food'
    | '/transit'
    | '/translate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CulturalRoute: typeof CulturalRoute
  FactCheckRoute: typeof FactCheckRoute
  FoodRoute: typeof FoodRoute
  TransitRoute: typeof TransitRoute
  TranslateRoute: typeof TranslateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/translate': {
      id: '/translate'
      path: '/translate'
      fullPath: '/translate'
      preLoaderRoute: typeof TranslateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transit': {
      id: '/transit'
      path: '/transit'
      fullPath: '/transit'
      preLoaderRoute: typeof TransitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food': {
      id: '/food'
      path: '/food'
      fullPath: '/food'
      preLoaderRoute: typeof FoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fact-check': {
      id: '/fact-check'
      path: '/fact-check'
      fullPath: '/fact-check'
      preLoaderRoute: typeof FactCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cultural': {
      id: '/cultural'
      path: '/cultural'
      fullPath: '/cultural'
      preLoaderRoute: typeof CulturalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CulturalRoute: CulturalRoute,
  FactCheckRoute: FactCheckRoute,
  FoodRoute: FoodRoute,
  TransitRoute: TransitRoute,
  TranslateRoute: TranslateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
